service: YMaps-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  lambdaHashingVersion: '20201221'

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/v1/placemarks
          method: GET
          cors: true
      - http:
          path: /api/v1/placemarks/{id}
          method: GET
          cors: true
      - http:
          path: /api/v1/placemarks
          method: POST
          cors: true
      - http:
          path: /api/v1/placemarks/{id}
          method: PUT
          cors: true
      - http:
          path: /api/v1/placemarks/{id}
          method: DELETE
          cors: true

plugins:
  - serverless-plugin-typescript
