# This workflow will push code to AWS Lambda Function using serverless framework

name: Deploy main branch

on:
  push:
<<<<<<< Updated upstream
    branches: [ main ]
=======
    branches:
      - main
>>>>>>> Stashed changes

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
<<<<<<< Updated upstream
=======
    defaults:
      run:
        working-directory: /home/runner/work/YMaps/backend
>>>>>>> Stashed changes
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js '16.x'
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
<<<<<<< Updated upstream
      run: npm ci
    - name: Serverless deploy
=======
      run: npm install
    - name: Serverless deploy

>>>>>>> Stashed changes
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
